---
# Workflow for deploying static HTML site to GitHub Pages
name: Deploy Cover Letter Generator to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
  # Runs on pushes to pull requests targeting main
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued. However, do NOT cancel
# in-progress runs as we want to allow these production deployments
# to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and validate the static site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          echo "Validating HTML files..."
          # Check if HTML files exist and are valid
          if [ -f "index.html" ]; then
            echo "✓ index.html found"
          else
            echo "✗ index.html not found"
            exit 1
          fi

      - name: Validate CSS and JS
        run: |
          echo "Validating CSS and JS files..."
          if [ -f "styles.css" ]; then
            echo "✓ styles.css found"
          else
            echo "✗ styles.css not found"
            exit 1
          fi
          if [ -f "script.js" ]; then
            echo "✓ script.js found"
          else
            echo "✗ script.js not found"
            exit 1
          fi

      - name: Setup Pages (for PR builds)
        if: github.event_name == 'pull_request'
        uses: actions/configure-pages@v5

      - name: Upload artifact (for PR builds)
        if: github.event_name == 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  # Deploy job - only runs on main branch pushes or manual dispatch
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload static site files
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
